# Generated by Django 5.1.7 on 2025-07-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the phone.', null=True, upload_to='phone_images/'),
        ),
        migrations.AddField(
            model_name='phone',
            name='memory',
            field=models.IntegerField(default=128, help_text='Memory of the phone in GB.'),
        ),
    ]
