# Generated by Django 5.1.7 on 2025-07-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='camera_quality',
            field=models.CharField(blank=True, help_text='Camera quality (e.g., 12MP, 48MP)', max_length=50),
        ),
        migrations.AddField(
            model_name='phone',
            name='color',
            field=models.CharField(blank=True, help_text='Color of the phone', max_length=50),
        ),
    ]
